### ISSUE TITLE
Attempt to build the PRNG executables fails

### ISSUE THREAD

**Issue by Ricky-Tigg** [jameshanlon/prng-testing#2]
**OS:** Fedora (edition 39) x86_64 | **Linux kernel v.:** 6.5.x.

Hello. Thanks to your "_[manual intervention may be required](https://github.com/jameshanlon/prng-testing#getting-started)_" in respect to `./install_deps.sh`, I am prepared. There are some
- "`mkdir: cannot create directory '(...)': File exists`",
- "`rm: cannot remove '(...)': No such file or directory`",
- warnings.

Attempt to build the PRNG executables not successful; _stderr_:
```
src/mersenne_twister.cpp:6:10: fatal error: boost/random/mersenne_twister.hpp: No such file or directory
    6 | #include <boost/random/mersenne_twister.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:102: bin/hwd_mersenne_twister] Error 1
make: *** Waiting for unfinished jobs....
src/mersenne_twister.cpp:6:10: fatal error: boost/random/mersenne_twister.hpp: No such file or directory
    6 | #include <boost/random/mersenne_twister.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:132: bin/ze_mersenne_twister] Error 1
src/mersenne_twister.cpp:6:10: fatal error: boost/random/mersenne_twister.hpp: No such file or directory
    6 | #include <boost/random/mersenne_twister.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:58: bin/mersenne_twister] Error 1
```

**Comment by jameshanlon** [comment]
Hi Ricky. It looks like you don't have boost installed. Feel free to submit a patch to fix the other issues, otherwise I'll try and get around to fixing them soon.

**Comment by Ricky-Tigg** [comment]
```
$ dnf rq --userinstalled --qf %{version} boost
1.81.0
```
New attempt; errors produced. _stderr_ has grown big enough to be joined as a file: [stderr.txt](https://github.com/jameshanlon/prng-testing/files/13415882/stderr.txt).

**Comment by Ricky-Tigg** [comment]
_No action within a reasonable time frame_

From which to draw a conclusion.
